server:
  port: 9000                           # The port your Auth server will run on (http://localhost:9000)

app:
  issuer: http://localhost:9000        # The "issuer" value in your JWT tokens (must be HTTPS in production)
  audience: medicare-api               # The intended audience for tokens; usually matches your API
  access-token-mins: 15                # Token validity time in minutes for Access Tokens
  refresh-token-days: 7                # Token validity time in days for Refresh Tokens
  jwks:
    key-id: auth-key-2025              # Unique key ID (kid) for JWT signing; rotate keys by changing this
    rsa:
      public-key-b64: ${PUBLIC_KEY}
      private-key-b64: ${PRIVATE_KEY}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}            # Google OAuth2 Client ID (set in environment variables)
            client-secret: ${GOOGLE_CLIENT_SECRET}    # Google OAuth2 Client Secret (also in environment variables)
            redirect-uri: http://localhost:9000/login/oauth2/code/google
            # Where Google will redirect after login (must match in Google console)

            scope: openid, profile, email            # Scopes requested from Google (basic profile info + email)
        provider:
          google:
            issuer-uri: https://accounts.google.com  # Google's OpenID Connect issuer URI (used for JWT validation)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: tx-   # optional (we use executeInTransaction in processor)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true   # ensure idempotent producer
        acks: all
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        transaction:
          id:
            prefix: tx-
  data:
    redis:
      host: localhost
      port: 6379
