#spring.application.name=Auth-Service
##database properties
#spring.data.mongodb.uri=mongodb+srv://${mongoDB_username}:${mongoDB_Password}@medicare.qzyf5vd.mongodb.net/?retryWrites=true&w=majority
#spring.data.mongodb.database=Medicare
#cloud.openfeign.discovery.enabled=true
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#server.address=0.0.0.0
#management.endpoint.health.group.custom.show-components=always
#management.endpoint.health.group.custom.show-details=always
## expose actuators
#management.endpoints.web.exposure.include=health,info,prometheus,metrics,env,health/readiness
#management.endpoint.health.show-details=when_authorized
#management.endpoint.health.enabled=true
#management.server.port=${MANAGEMENT_PORT:8081}