spring.application.name=Notification-Service
aws.accessKey=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
spring.profiles.active=prod

# email properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.config.use-legacy-processing=true