spring.application.name=Service-Registry
server.port=8761
server.address=0.0.0.0
management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always
management.endpoints.web.exposure.include= health,info
# Eureka settings
eureka.instance.hostname=service-registry
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
