spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      server:
        webflux:
          routes:
            - id: AUTH-SERVICE
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - name: JwtAuth
            - id: INVENTORY-SERVICE
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/inventory/**
              filters:
                - name: JwtAuth
            - id: NOTIFICATION-SERVICE
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notification/**
              filters:
                - name: JwtAuth
            - id: ORDER-SERVICE
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order/**
              filters:
                - name: JwtAuth
            - id: PAYMENT-SERVICE
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment/**
              filters:
                - name: JwtAuth
            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product/**
              filters:
                - name: JwtAuth
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**
              filters:
                - name: JwtAuth
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info