spring.application.name=Api-Gateway
server.port=8765
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.main.web-application-type=reactive
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
server.address=0.0.0.0
management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always