spring.application.name=Payment-Service
server.port=8070
server.address=0.0.0.0
management.endpoint.health.group.custom.show-components=always
management.endpoint.health.group.custom.show-details=always