eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DOCKER_EUREKA_HOST:localhost}:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info
spring:
  profiles:
    active: dev
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
