eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DOCKER_EUREKA_HOST:localhost}:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health,info
openapi:
  service:
    title: order-service doc
    version: 1.0.0
    url: http://${DOCKER_API_GATEWAY_HOST:localhost}:8765 #api gateway url
springdoc:
  api-docs:
    path: /order-service/v3/api-docs
  swagger-ui:
    path: /order-service/swagger-ui.html