###
# group: Authentication
# @name signup
POST http://localhost:8765/auth-service/auth/signUp
Content-Type: application/json

{
  "firstName": "Subhajit",
  "lastName": "Patra",
  "email": "subhajitpatra498@gmail.com",
  "password": "Subha@123456",
  "role": "admin"
}
